-- Add optimistic locking version columns to 8 document tables
ALTER TABLE "RCV_RECEIPT_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RCV_INSPECTION_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RCV_DISCREPANCY_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ONT_ISSUE_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ONT_RETURN_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ONT_REQUISITION_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MTL_TRANSFER_HEADERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WMS_JOB_ORDERS" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 0;
